# Generated by Django 2.2.16 on 2020-10-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='date',
            new_name='dateCreated',
        ),
        migrations.AddField(
            model_name='parcel',
            name='dateSent',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date sent'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='isSent',
            field=models.BooleanField(default=False),
        ),
    ]
