# Generated by Django 2.2.16 on 2020-10-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201027_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='dateSent',
            field=models.DateTimeField(null=True, verbose_name='date sent'),
        ),
    ]
