# Generated by Django 2.2.16 on 2020-10-29 17:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201029_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, region=None, unique=True),
        ),
    ]
