# Generated by Django 2.2.16 on 2020-10-30 00:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20201029_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiverContact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='senderContact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, null=True, region=None, unique=True),
        ),
    ]
