# Generated by Django 2.2.16 on 2020-10-30 00:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20201030_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='receiverContact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='senderContact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, region=None, unique=True),
        ),
    ]
