# Generated by Django 2.2.16 on 2020-10-30 20:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20201030_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='receiverContact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, region=None),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='senderContact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, region=None),
        ),
    ]
