# Generated by Django 2.2.16 on 2020-10-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_parcel_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='isDeclined',
            field=models.BooleanField(default=False),
        ),
    ]
