# Generated by Django 2.2.16 on 2020-10-08 21:12

import application.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Admin', 'ADMIN'), ('Registered User', 'REGISTERED_USER'), ('None', 'NONE')], default=application.utils.RoleEnum('Registered User'), max_length=50)),
            ],
        ),
    ]
