# Generated by Django 2.2.16 on 2020-10-08 23:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=200, max_digits=300)),
                ('latitude', models.DecimalField(decimal_places=200, max_digits=300)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_destination', to='application.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations', models.ManyToManyField(to='application.Destination')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train', to='application.Train')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('destination_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_from', to='application.Destination')),
                ('destination_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_to', to='application.Destination')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='application.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='application.User')),
            ],
        ),
    ]
