# Generated by Django 2.2.16 on 2020-10-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_destination_parcel_route_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordOne',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passwordRepeat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
