# Generated by Django 2.2.16 on 2020-10-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20201012_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='isDelivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
