# Generated by Django 2.2.16 on 2020-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201012_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=254),
        ),
    ]
