# Generated by Django 2.2.16 on 2020-10-14 09:41

import application.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20201014_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(application.utils.RoleEnum('Admin'), 'Admin'), (application.utils.RoleEnum('Registered User'), 'Registered User'), (application.utils.RoleEnum('None'), 'None')], default=application.utils.RoleEnum('Registered User'), max_length=50),
        ),
    ]
