# Generated by Django 2.2.16 on 2020-10-14 09:44

import application.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20201014_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('Registered User', 'REGISTERED_USER'), ('None', 'NONE')], default=application.utils.RoleEnum('Registered User'), max_length=50),
        ),
    ]
