# Generated by Django 2.2.16 on 2020-10-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20201014_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='start_destination',
            field=models.CharField(max_length=200),
        ),
    ]
