# Generated by Django 2.2.16 on 2020-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20201021_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='destination_from',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='destination_to',
            field=models.CharField(max_length=200),
        ),
    ]
