# Generated by Django 2.2.16 on 2020-10-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20201021_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
